version: 2
jobs:
  build:
    working_directory: work
    docker:
      - image: "circleci/openjdk:8"
    steps:
      - checkout
      - restore_cache:
          key: maven-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}
      - run: mvn install
      - store_test_results:
          path: target/surefire-reports
      - store_test_results:
          path: target/failsafe-reports
      - run: "curl -fv -u $CIRCLE_TOKEN: -X POST https://circleci.com/api/v1.1/project/github/phoebus-games/roulette/tree/master"
      - run: "curl -fv -u $CIRCLE_TOKEN: -X POST https://circleci.com/api/v1.1/project/github/phoebus-games/classic-slot/tree/master"
